server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false

spring:
  logstash:
    server: ${${LOGSTASH_SERVICE}.service.host}
    port: ${${LOGSTASH_SERVICE}.service.port}
  zipkin:
    base-url: http://${${ZIPKIN_SERVICE}.service.host}:${${ZIPKIN_SERVICE}.service.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    distribution:
      percentiles-histogram.http.server.requests: false
      percentiles.http.server.requests: 0.5, 0.9, 0.95, 0.99, 0.999
      sla.http.server.requests: 500ms, 2000ms
