apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-service-accounts
  labels:
    app: k8s-service-accounts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-service-accounts
  template:
    metadata:
      labels:
        app: k8s-service-accounts
    spec:
      containers:
        - name: containerized-accounts
          image: tanerdiler/service-accounts-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 2222